/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.jike.mobile.appsearch.thirft;

import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.BitSet;
import java.util.Collections;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ApkFullProperty implements org.apache.thrift.TBase<ApkFullProperty, ApkFullProperty._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ApkFullProperty");

  private static final org.apache.thrift.protocol.TField PACKAGE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("packageName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField VERSION_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("versionName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField VERSION_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("versionCode", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField USES_PERMISSON_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("usesPermissonList", org.apache.thrift.protocol.TType.LIST, (short)4);
  private static final org.apache.thrift.protocol.TField USES_FEATURE_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("usesFeatureList", org.apache.thrift.protocol.TType.LIST, (short)5);
  private static final org.apache.thrift.protocol.TField MIN_SDK_FIELD_DESC = new org.apache.thrift.protocol.TField("minSDK", org.apache.thrift.protocol.TType.I32, (short)6);
  private static final org.apache.thrift.protocol.TField TARGET_SDK_FIELD_DESC = new org.apache.thrift.protocol.TField("targetSDK", org.apache.thrift.protocol.TType.I32, (short)7);
  private static final org.apache.thrift.protocol.TField SMALL_SCREEN_FIELD_DESC = new org.apache.thrift.protocol.TField("smallScreen", org.apache.thrift.protocol.TType.BOOL, (short)8);
  private static final org.apache.thrift.protocol.TField NORMAL_SCREEN_FIELD_DESC = new org.apache.thrift.protocol.TField("normalScreen", org.apache.thrift.protocol.TType.BOOL, (short)9);
  private static final org.apache.thrift.protocol.TField LARGE_SCREEN_FIELD_DESC = new org.apache.thrift.protocol.TField("largeScreen", org.apache.thrift.protocol.TType.BOOL, (short)10);
  private static final org.apache.thrift.protocol.TField XLARGE_SCREEN_FIELD_DESC = new org.apache.thrift.protocol.TField("xlargeScreen", org.apache.thrift.protocol.TType.BOOL, (short)11);
  private static final org.apache.thrift.protocol.TField SIGNATURE_FIELD_DESC = new org.apache.thrift.protocol.TField("signature", org.apache.thrift.protocol.TType.STRING, (short)12);
  private static final org.apache.thrift.protocol.TField ICON_FIELD_DESC = new org.apache.thrift.protocol.TField("icon", org.apache.thrift.protocol.TType.STRING, (short)13);
  private static final org.apache.thrift.protocol.TField APP_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("appName", org.apache.thrift.protocol.TType.MAP, (short)14);
  private static final org.apache.thrift.protocol.TField ADS_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("AdsList", org.apache.thrift.protocol.TType.LIST, (short)15);
  private static final org.apache.thrift.protocol.TField APK_SIZE_FIELD_DESC = new org.apache.thrift.protocol.TField("apkSize", org.apache.thrift.protocol.TType.DOUBLE, (short)16);
  private static final org.apache.thrift.protocol.TField SECURITY_LEVEL_FIELD_DESC = new org.apache.thrift.protocol.TField("securityLevel", org.apache.thrift.protocol.TType.I32, (short)17);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ApkFullPropertyStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ApkFullPropertyTupleSchemeFactory());
  }

  public String packageName; // required
  public String versionName; // required
  public String versionCode; // required
  public List<String> usesPermissonList; // required
  public List<String> usesFeatureList; // required
  public int minSDK; // required
  public int targetSDK; // required
  public boolean smallScreen; // required
  public boolean normalScreen; // required
  public boolean largeScreen; // required
  public boolean xlargeScreen; // required
  public String signature; // required
  public ByteBuffer icon; // required
  public Map<String,String> appName; // required
  public List<String> AdsList; // required
  public double apkSize; // required
  public int securityLevel; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PACKAGE_NAME((short)1, "packageName"),
    VERSION_NAME((short)2, "versionName"),
    VERSION_CODE((short)3, "versionCode"),
    USES_PERMISSON_LIST((short)4, "usesPermissonList"),
    USES_FEATURE_LIST((short)5, "usesFeatureList"),
    MIN_SDK((short)6, "minSDK"),
    TARGET_SDK((short)7, "targetSDK"),
    SMALL_SCREEN((short)8, "smallScreen"),
    NORMAL_SCREEN((short)9, "normalScreen"),
    LARGE_SCREEN((short)10, "largeScreen"),
    XLARGE_SCREEN((short)11, "xlargeScreen"),
    SIGNATURE((short)12, "signature"),
    ICON((short)13, "icon"),
    APP_NAME((short)14, "appName"),
    ADS_LIST((short)15, "AdsList"),
    APK_SIZE((short)16, "apkSize"),
    SECURITY_LEVEL((short)17, "securityLevel");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PACKAGE_NAME
          return PACKAGE_NAME;
        case 2: // VERSION_NAME
          return VERSION_NAME;
        case 3: // VERSION_CODE
          return VERSION_CODE;
        case 4: // USES_PERMISSON_LIST
          return USES_PERMISSON_LIST;
        case 5: // USES_FEATURE_LIST
          return USES_FEATURE_LIST;
        case 6: // MIN_SDK
          return MIN_SDK;
        case 7: // TARGET_SDK
          return TARGET_SDK;
        case 8: // SMALL_SCREEN
          return SMALL_SCREEN;
        case 9: // NORMAL_SCREEN
          return NORMAL_SCREEN;
        case 10: // LARGE_SCREEN
          return LARGE_SCREEN;
        case 11: // XLARGE_SCREEN
          return XLARGE_SCREEN;
        case 12: // SIGNATURE
          return SIGNATURE;
        case 13: // ICON
          return ICON;
        case 14: // APP_NAME
          return APP_NAME;
        case 15: // ADS_LIST
          return ADS_LIST;
        case 16: // APK_SIZE
          return APK_SIZE;
        case 17: // SECURITY_LEVEL
          return SECURITY_LEVEL;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __MINSDK_ISSET_ID = 0;
  private static final int __TARGETSDK_ISSET_ID = 1;
  private static final int __SMALLSCREEN_ISSET_ID = 2;
  private static final int __NORMALSCREEN_ISSET_ID = 3;
  private static final int __LARGESCREEN_ISSET_ID = 4;
  private static final int __XLARGESCREEN_ISSET_ID = 5;
  private static final int __APKSIZE_ISSET_ID = 6;
  private static final int __SECURITYLEVEL_ISSET_ID = 7;
  private BitSet __isset_bit_vector = new BitSet(8);
  private _Fields optionals[] = {_Fields.SECURITY_LEVEL};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PACKAGE_NAME, new org.apache.thrift.meta_data.FieldMetaData("packageName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VERSION_NAME, new org.apache.thrift.meta_data.FieldMetaData("versionName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VERSION_CODE, new org.apache.thrift.meta_data.FieldMetaData("versionCode", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USES_PERMISSON_LIST, new org.apache.thrift.meta_data.FieldMetaData("usesPermissonList", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.USES_FEATURE_LIST, new org.apache.thrift.meta_data.FieldMetaData("usesFeatureList", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.MIN_SDK, new org.apache.thrift.meta_data.FieldMetaData("minSDK", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TARGET_SDK, new org.apache.thrift.meta_data.FieldMetaData("targetSDK", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SMALL_SCREEN, new org.apache.thrift.meta_data.FieldMetaData("smallScreen", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.NORMAL_SCREEN, new org.apache.thrift.meta_data.FieldMetaData("normalScreen", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.LARGE_SCREEN, new org.apache.thrift.meta_data.FieldMetaData("largeScreen", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.XLARGE_SCREEN, new org.apache.thrift.meta_data.FieldMetaData("xlargeScreen", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.SIGNATURE, new org.apache.thrift.meta_data.FieldMetaData("signature", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ICON, new org.apache.thrift.meta_data.FieldMetaData("icon", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.APP_NAME, new org.apache.thrift.meta_data.FieldMetaData("appName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.ADS_LIST, new org.apache.thrift.meta_data.FieldMetaData("AdsList", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.APK_SIZE, new org.apache.thrift.meta_data.FieldMetaData("apkSize", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.SECURITY_LEVEL, new org.apache.thrift.meta_data.FieldMetaData("securityLevel", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ApkFullProperty.class, metaDataMap);
  }

  public ApkFullProperty() {
    this.minSDK = 0;

    this.targetSDK = 0;

    this.smallScreen = true;

    this.normalScreen = true;

    this.largeScreen = true;

    this.xlargeScreen = true;

    this.signature = "";

    this.apkSize = (double)0;

    this.securityLevel = 0;

  }

  public ApkFullProperty(
    String packageName,
    String versionName,
    String versionCode,
    List<String> usesPermissonList,
    List<String> usesFeatureList,
    int minSDK,
    int targetSDK,
    boolean smallScreen,
    boolean normalScreen,
    boolean largeScreen,
    boolean xlargeScreen,
    String signature,
    ByteBuffer icon,
    Map<String,String> appName,
    List<String> AdsList,
    double apkSize)
  {
    this();
    this.packageName = packageName;
    this.versionName = versionName;
    this.versionCode = versionCode;
    this.usesPermissonList = usesPermissonList;
    this.usesFeatureList = usesFeatureList;
    this.minSDK = minSDK;
    setMinSDKIsSet(true);
    this.targetSDK = targetSDK;
    setTargetSDKIsSet(true);
    this.smallScreen = smallScreen;
    setSmallScreenIsSet(true);
    this.normalScreen = normalScreen;
    setNormalScreenIsSet(true);
    this.largeScreen = largeScreen;
    setLargeScreenIsSet(true);
    this.xlargeScreen = xlargeScreen;
    setXlargeScreenIsSet(true);
    this.signature = signature;
    this.icon = icon;
    this.appName = appName;
    this.AdsList = AdsList;
    this.apkSize = apkSize;
    setApkSizeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ApkFullProperty(ApkFullProperty other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    if (other.isSetPackageName()) {
      this.packageName = other.packageName;
    }
    if (other.isSetVersionName()) {
      this.versionName = other.versionName;
    }
    if (other.isSetVersionCode()) {
      this.versionCode = other.versionCode;
    }
    if (other.isSetUsesPermissonList()) {
      List<String> __this__usesPermissonList = new ArrayList<String>();
      for (String other_element : other.usesPermissonList) {
        __this__usesPermissonList.add(other_element);
      }
      this.usesPermissonList = __this__usesPermissonList;
    }
    if (other.isSetUsesFeatureList()) {
      List<String> __this__usesFeatureList = new ArrayList<String>();
      for (String other_element : other.usesFeatureList) {
        __this__usesFeatureList.add(other_element);
      }
      this.usesFeatureList = __this__usesFeatureList;
    }
    this.minSDK = other.minSDK;
    this.targetSDK = other.targetSDK;
    this.smallScreen = other.smallScreen;
    this.normalScreen = other.normalScreen;
    this.largeScreen = other.largeScreen;
    this.xlargeScreen = other.xlargeScreen;
    if (other.isSetSignature()) {
      this.signature = other.signature;
    }
    if (other.isSetIcon()) {
      this.icon = org.apache.thrift.TBaseHelper.copyBinary(other.icon);
;
    }
    if (other.isSetAppName()) {
      Map<String,String> __this__appName = new HashMap<String,String>();
      for (Map.Entry<String, String> other_element : other.appName.entrySet()) {

        String other_element_key = other_element.getKey();
        String other_element_value = other_element.getValue();

        String __this__appName_copy_key = other_element_key;

        String __this__appName_copy_value = other_element_value;

        __this__appName.put(__this__appName_copy_key, __this__appName_copy_value);
      }
      this.appName = __this__appName;
    }
    if (other.isSetAdsList()) {
      List<String> __this__AdsList = new ArrayList<String>();
      for (String other_element : other.AdsList) {
        __this__AdsList.add(other_element);
      }
      this.AdsList = __this__AdsList;
    }
    this.apkSize = other.apkSize;
    this.securityLevel = other.securityLevel;
  }

  public ApkFullProperty deepCopy() {
    return new ApkFullProperty(this);
  }

  @Override
  public void clear() {
    this.packageName = null;
    this.versionName = null;
    this.versionCode = null;
    this.usesPermissonList = null;
    this.usesFeatureList = null;
    this.minSDK = 0;

    this.targetSDK = 0;

    this.smallScreen = true;

    this.normalScreen = true;

    this.largeScreen = true;

    this.xlargeScreen = true;

    this.signature = "";

    this.icon = null;
    this.appName = null;
    this.AdsList = null;
    this.apkSize = (double)0;

    this.securityLevel = 0;

  }

  public String getPackageName() {
    return this.packageName;
  }

  public ApkFullProperty setPackageName(String packageName) {
    this.packageName = packageName;
    return this;
  }

  public void unsetPackageName() {
    this.packageName = null;
  }

  /** Returns true if field packageName is set (has been assigned a value) and false otherwise */
  public boolean isSetPackageName() {
    return this.packageName != null;
  }

  public void setPackageNameIsSet(boolean value) {
    if (!value) {
      this.packageName = null;
    }
  }

  public String getVersionName() {
    return this.versionName;
  }

  public ApkFullProperty setVersionName(String versionName) {
    this.versionName = versionName;
    return this;
  }

  public void unsetVersionName() {
    this.versionName = null;
  }

  /** Returns true if field versionName is set (has been assigned a value) and false otherwise */
  public boolean isSetVersionName() {
    return this.versionName != null;
  }

  public void setVersionNameIsSet(boolean value) {
    if (!value) {
      this.versionName = null;
    }
  }

  public String getVersionCode() {
    return this.versionCode;
  }

  public ApkFullProperty setVersionCode(String versionCode) {
    this.versionCode = versionCode;
    return this;
  }

  public void unsetVersionCode() {
    this.versionCode = null;
  }

  /** Returns true if field versionCode is set (has been assigned a value) and false otherwise */
  public boolean isSetVersionCode() {
    return this.versionCode != null;
  }

  public void setVersionCodeIsSet(boolean value) {
    if (!value) {
      this.versionCode = null;
    }
  }

  public int getUsesPermissonListSize() {
    return (this.usesPermissonList == null) ? 0 : this.usesPermissonList.size();
  }

  public java.util.Iterator<String> getUsesPermissonListIterator() {
    return (this.usesPermissonList == null) ? null : this.usesPermissonList.iterator();
  }

  public void addToUsesPermissonList(String elem) {
    if (this.usesPermissonList == null) {
      this.usesPermissonList = new ArrayList<String>();
    }
    this.usesPermissonList.add(elem);
  }

  public List<String> getUsesPermissonList() {
    return this.usesPermissonList;
  }

  public ApkFullProperty setUsesPermissonList(List<String> usesPermissonList) {
    this.usesPermissonList = usesPermissonList;
    return this;
  }

  public void unsetUsesPermissonList() {
    this.usesPermissonList = null;
  }

  /** Returns true if field usesPermissonList is set (has been assigned a value) and false otherwise */
  public boolean isSetUsesPermissonList() {
    return this.usesPermissonList != null;
  }

  public void setUsesPermissonListIsSet(boolean value) {
    if (!value) {
      this.usesPermissonList = null;
    }
  }

  public int getUsesFeatureListSize() {
    return (this.usesFeatureList == null) ? 0 : this.usesFeatureList.size();
  }

  public java.util.Iterator<String> getUsesFeatureListIterator() {
    return (this.usesFeatureList == null) ? null : this.usesFeatureList.iterator();
  }

  public void addToUsesFeatureList(String elem) {
    if (this.usesFeatureList == null) {
      this.usesFeatureList = new ArrayList<String>();
    }
    this.usesFeatureList.add(elem);
  }

  public List<String> getUsesFeatureList() {
    return this.usesFeatureList;
  }

  public ApkFullProperty setUsesFeatureList(List<String> usesFeatureList) {
    this.usesFeatureList = usesFeatureList;
    return this;
  }

  public void unsetUsesFeatureList() {
    this.usesFeatureList = null;
  }

  /** Returns true if field usesFeatureList is set (has been assigned a value) and false otherwise */
  public boolean isSetUsesFeatureList() {
    return this.usesFeatureList != null;
  }

  public void setUsesFeatureListIsSet(boolean value) {
    if (!value) {
      this.usesFeatureList = null;
    }
  }

  public int getMinSDK() {
    return this.minSDK;
  }

  public ApkFullProperty setMinSDK(int minSDK) {
    this.minSDK = minSDK;
    setMinSDKIsSet(true);
    return this;
  }

  public void unsetMinSDK() {
    __isset_bit_vector.clear(__MINSDK_ISSET_ID);
  }

  /** Returns true if field minSDK is set (has been assigned a value) and false otherwise */
  public boolean isSetMinSDK() {
    return __isset_bit_vector.get(__MINSDK_ISSET_ID);
  }

  public void setMinSDKIsSet(boolean value) {
    __isset_bit_vector.set(__MINSDK_ISSET_ID, value);
  }

  public int getTargetSDK() {
    return this.targetSDK;
  }

  public ApkFullProperty setTargetSDK(int targetSDK) {
    this.targetSDK = targetSDK;
    setTargetSDKIsSet(true);
    return this;
  }

  public void unsetTargetSDK() {
    __isset_bit_vector.clear(__TARGETSDK_ISSET_ID);
  }

  /** Returns true if field targetSDK is set (has been assigned a value) and false otherwise */
  public boolean isSetTargetSDK() {
    return __isset_bit_vector.get(__TARGETSDK_ISSET_ID);
  }

  public void setTargetSDKIsSet(boolean value) {
    __isset_bit_vector.set(__TARGETSDK_ISSET_ID, value);
  }

  public boolean isSmallScreen() {
    return this.smallScreen;
  }

  public ApkFullProperty setSmallScreen(boolean smallScreen) {
    this.smallScreen = smallScreen;
    setSmallScreenIsSet(true);
    return this;
  }

  public void unsetSmallScreen() {
    __isset_bit_vector.clear(__SMALLSCREEN_ISSET_ID);
  }

  /** Returns true if field smallScreen is set (has been assigned a value) and false otherwise */
  public boolean isSetSmallScreen() {
    return __isset_bit_vector.get(__SMALLSCREEN_ISSET_ID);
  }

  public void setSmallScreenIsSet(boolean value) {
    __isset_bit_vector.set(__SMALLSCREEN_ISSET_ID, value);
  }

  public boolean isNormalScreen() {
    return this.normalScreen;
  }

  public ApkFullProperty setNormalScreen(boolean normalScreen) {
    this.normalScreen = normalScreen;
    setNormalScreenIsSet(true);
    return this;
  }

  public void unsetNormalScreen() {
    __isset_bit_vector.clear(__NORMALSCREEN_ISSET_ID);
  }

  /** Returns true if field normalScreen is set (has been assigned a value) and false otherwise */
  public boolean isSetNormalScreen() {
    return __isset_bit_vector.get(__NORMALSCREEN_ISSET_ID);
  }

  public void setNormalScreenIsSet(boolean value) {
    __isset_bit_vector.set(__NORMALSCREEN_ISSET_ID, value);
  }

  public boolean isLargeScreen() {
    return this.largeScreen;
  }

  public ApkFullProperty setLargeScreen(boolean largeScreen) {
    this.largeScreen = largeScreen;
    setLargeScreenIsSet(true);
    return this;
  }

  public void unsetLargeScreen() {
    __isset_bit_vector.clear(__LARGESCREEN_ISSET_ID);
  }

  /** Returns true if field largeScreen is set (has been assigned a value) and false otherwise */
  public boolean isSetLargeScreen() {
    return __isset_bit_vector.get(__LARGESCREEN_ISSET_ID);
  }

  public void setLargeScreenIsSet(boolean value) {
    __isset_bit_vector.set(__LARGESCREEN_ISSET_ID, value);
  }

  public boolean isXlargeScreen() {
    return this.xlargeScreen;
  }

  public ApkFullProperty setXlargeScreen(boolean xlargeScreen) {
    this.xlargeScreen = xlargeScreen;
    setXlargeScreenIsSet(true);
    return this;
  }

  public void unsetXlargeScreen() {
    __isset_bit_vector.clear(__XLARGESCREEN_ISSET_ID);
  }

  /** Returns true if field xlargeScreen is set (has been assigned a value) and false otherwise */
  public boolean isSetXlargeScreen() {
    return __isset_bit_vector.get(__XLARGESCREEN_ISSET_ID);
  }

  public void setXlargeScreenIsSet(boolean value) {
    __isset_bit_vector.set(__XLARGESCREEN_ISSET_ID, value);
  }

  public String getSignature() {
    return this.signature;
  }

  public ApkFullProperty setSignature(String signature) {
    this.signature = signature;
    return this;
  }

  public void unsetSignature() {
    this.signature = null;
  }

  /** Returns true if field signature is set (has been assigned a value) and false otherwise */
  public boolean isSetSignature() {
    return this.signature != null;
  }

  public void setSignatureIsSet(boolean value) {
    if (!value) {
      this.signature = null;
    }
  }

  public byte[] getIcon() {
    setIcon(org.apache.thrift.TBaseHelper.rightSize(icon));
    return icon == null ? null : icon.array();
  }

  public ByteBuffer bufferForIcon() {
    return icon;
  }

  public ApkFullProperty setIcon(byte[] icon) {
    setIcon(icon == null ? (ByteBuffer)null : ByteBuffer.wrap(icon));
    return this;
  }

  public ApkFullProperty setIcon(ByteBuffer icon) {
    this.icon = icon;
    return this;
  }

  public void unsetIcon() {
    this.icon = null;
  }

  /** Returns true if field icon is set (has been assigned a value) and false otherwise */
  public boolean isSetIcon() {
    return this.icon != null;
  }

  public void setIconIsSet(boolean value) {
    if (!value) {
      this.icon = null;
    }
  }

  public int getAppNameSize() {
    return (this.appName == null) ? 0 : this.appName.size();
  }

  public void putToAppName(String key, String val) {
    if (this.appName == null) {
      this.appName = new HashMap<String,String>();
    }
    this.appName.put(key, val);
  }

  public Map<String,String> getAppName() {
    return this.appName;
  }

  public ApkFullProperty setAppName(Map<String,String> appName) {
    this.appName = appName;
    return this;
  }

  public void unsetAppName() {
    this.appName = null;
  }

  /** Returns true if field appName is set (has been assigned a value) and false otherwise */
  public boolean isSetAppName() {
    return this.appName != null;
  }

  public void setAppNameIsSet(boolean value) {
    if (!value) {
      this.appName = null;
    }
  }

  public int getAdsListSize() {
    return (this.AdsList == null) ? 0 : this.AdsList.size();
  }

  public java.util.Iterator<String> getAdsListIterator() {
    return (this.AdsList == null) ? null : this.AdsList.iterator();
  }

  public void addToAdsList(String elem) {
    if (this.AdsList == null) {
      this.AdsList = new ArrayList<String>();
    }
    this.AdsList.add(elem);
  }

  public List<String> getAdsList() {
    return this.AdsList;
  }

  public ApkFullProperty setAdsList(List<String> AdsList) {
    this.AdsList = AdsList;
    return this;
  }

  public void unsetAdsList() {
    this.AdsList = null;
  }

  /** Returns true if field AdsList is set (has been assigned a value) and false otherwise */
  public boolean isSetAdsList() {
    return this.AdsList != null;
  }

  public void setAdsListIsSet(boolean value) {
    if (!value) {
      this.AdsList = null;
    }
  }

  public double getApkSize() {
    return this.apkSize;
  }

  public ApkFullProperty setApkSize(double apkSize) {
    this.apkSize = apkSize;
    setApkSizeIsSet(true);
    return this;
  }

  public void unsetApkSize() {
    __isset_bit_vector.clear(__APKSIZE_ISSET_ID);
  }

  /** Returns true if field apkSize is set (has been assigned a value) and false otherwise */
  public boolean isSetApkSize() {
    return __isset_bit_vector.get(__APKSIZE_ISSET_ID);
  }

  public void setApkSizeIsSet(boolean value) {
    __isset_bit_vector.set(__APKSIZE_ISSET_ID, value);
  }

  public int getSecurityLevel() {
    return this.securityLevel;
  }

  public ApkFullProperty setSecurityLevel(int securityLevel) {
    this.securityLevel = securityLevel;
    setSecurityLevelIsSet(true);
    return this;
  }

  public void unsetSecurityLevel() {
    __isset_bit_vector.clear(__SECURITYLEVEL_ISSET_ID);
  }

  /** Returns true if field securityLevel is set (has been assigned a value) and false otherwise */
  public boolean isSetSecurityLevel() {
    return __isset_bit_vector.get(__SECURITYLEVEL_ISSET_ID);
  }

  public void setSecurityLevelIsSet(boolean value) {
    __isset_bit_vector.set(__SECURITYLEVEL_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PACKAGE_NAME:
      if (value == null) {
        unsetPackageName();
      } else {
        setPackageName((String)value);
      }
      break;

    case VERSION_NAME:
      if (value == null) {
        unsetVersionName();
      } else {
        setVersionName((String)value);
      }
      break;

    case VERSION_CODE:
      if (value == null) {
        unsetVersionCode();
      } else {
        setVersionCode((String)value);
      }
      break;

    case USES_PERMISSON_LIST:
      if (value == null) {
        unsetUsesPermissonList();
      } else {
        setUsesPermissonList((List<String>)value);
      }
      break;

    case USES_FEATURE_LIST:
      if (value == null) {
        unsetUsesFeatureList();
      } else {
        setUsesFeatureList((List<String>)value);
      }
      break;

    case MIN_SDK:
      if (value == null) {
        unsetMinSDK();
      } else {
        setMinSDK((Integer)value);
      }
      break;

    case TARGET_SDK:
      if (value == null) {
        unsetTargetSDK();
      } else {
        setTargetSDK((Integer)value);
      }
      break;

    case SMALL_SCREEN:
      if (value == null) {
        unsetSmallScreen();
      } else {
        setSmallScreen((Boolean)value);
      }
      break;

    case NORMAL_SCREEN:
      if (value == null) {
        unsetNormalScreen();
      } else {
        setNormalScreen((Boolean)value);
      }
      break;

    case LARGE_SCREEN:
      if (value == null) {
        unsetLargeScreen();
      } else {
        setLargeScreen((Boolean)value);
      }
      break;

    case XLARGE_SCREEN:
      if (value == null) {
        unsetXlargeScreen();
      } else {
        setXlargeScreen((Boolean)value);
      }
      break;

    case SIGNATURE:
      if (value == null) {
        unsetSignature();
      } else {
        setSignature((String)value);
      }
      break;

    case ICON:
      if (value == null) {
        unsetIcon();
      } else {
        setIcon((ByteBuffer)value);
      }
      break;

    case APP_NAME:
      if (value == null) {
        unsetAppName();
      } else {
        setAppName((Map<String,String>)value);
      }
      break;

    case ADS_LIST:
      if (value == null) {
        unsetAdsList();
      } else {
        setAdsList((List<String>)value);
      }
      break;

    case APK_SIZE:
      if (value == null) {
        unsetApkSize();
      } else {
        setApkSize((Double)value);
      }
      break;

    case SECURITY_LEVEL:
      if (value == null) {
        unsetSecurityLevel();
      } else {
        setSecurityLevel((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PACKAGE_NAME:
      return getPackageName();

    case VERSION_NAME:
      return getVersionName();

    case VERSION_CODE:
      return getVersionCode();

    case USES_PERMISSON_LIST:
      return getUsesPermissonList();

    case USES_FEATURE_LIST:
      return getUsesFeatureList();

    case MIN_SDK:
      return Integer.valueOf(getMinSDK());

    case TARGET_SDK:
      return Integer.valueOf(getTargetSDK());

    case SMALL_SCREEN:
      return Boolean.valueOf(isSmallScreen());

    case NORMAL_SCREEN:
      return Boolean.valueOf(isNormalScreen());

    case LARGE_SCREEN:
      return Boolean.valueOf(isLargeScreen());

    case XLARGE_SCREEN:
      return Boolean.valueOf(isXlargeScreen());

    case SIGNATURE:
      return getSignature();

    case ICON:
      return getIcon();

    case APP_NAME:
      return getAppName();

    case ADS_LIST:
      return getAdsList();

    case APK_SIZE:
      return Double.valueOf(getApkSize());

    case SECURITY_LEVEL:
      return Integer.valueOf(getSecurityLevel());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PACKAGE_NAME:
      return isSetPackageName();
    case VERSION_NAME:
      return isSetVersionName();
    case VERSION_CODE:
      return isSetVersionCode();
    case USES_PERMISSON_LIST:
      return isSetUsesPermissonList();
    case USES_FEATURE_LIST:
      return isSetUsesFeatureList();
    case MIN_SDK:
      return isSetMinSDK();
    case TARGET_SDK:
      return isSetTargetSDK();
    case SMALL_SCREEN:
      return isSetSmallScreen();
    case NORMAL_SCREEN:
      return isSetNormalScreen();
    case LARGE_SCREEN:
      return isSetLargeScreen();
    case XLARGE_SCREEN:
      return isSetXlargeScreen();
    case SIGNATURE:
      return isSetSignature();
    case ICON:
      return isSetIcon();
    case APP_NAME:
      return isSetAppName();
    case ADS_LIST:
      return isSetAdsList();
    case APK_SIZE:
      return isSetApkSize();
    case SECURITY_LEVEL:
      return isSetSecurityLevel();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ApkFullProperty)
      return this.equals((ApkFullProperty)that);
    return false;
  }

  public boolean equals(ApkFullProperty that) {
    if (that == null)
      return false;

    boolean this_present_packageName = true && this.isSetPackageName();
    boolean that_present_packageName = true && that.isSetPackageName();
    if (this_present_packageName || that_present_packageName) {
      if (!(this_present_packageName && that_present_packageName))
        return false;
      if (!this.packageName.equals(that.packageName))
        return false;
    }

    boolean this_present_versionName = true && this.isSetVersionName();
    boolean that_present_versionName = true && that.isSetVersionName();
    if (this_present_versionName || that_present_versionName) {
      if (!(this_present_versionName && that_present_versionName))
        return false;
      if (!this.versionName.equals(that.versionName))
        return false;
    }

    boolean this_present_versionCode = true && this.isSetVersionCode();
    boolean that_present_versionCode = true && that.isSetVersionCode();
    if (this_present_versionCode || that_present_versionCode) {
      if (!(this_present_versionCode && that_present_versionCode))
        return false;
      if (!this.versionCode.equals(that.versionCode))
        return false;
    }

    boolean this_present_usesPermissonList = true && this.isSetUsesPermissonList();
    boolean that_present_usesPermissonList = true && that.isSetUsesPermissonList();
    if (this_present_usesPermissonList || that_present_usesPermissonList) {
      if (!(this_present_usesPermissonList && that_present_usesPermissonList))
        return false;
      if (!this.usesPermissonList.equals(that.usesPermissonList))
        return false;
    }

    boolean this_present_usesFeatureList = true && this.isSetUsesFeatureList();
    boolean that_present_usesFeatureList = true && that.isSetUsesFeatureList();
    if (this_present_usesFeatureList || that_present_usesFeatureList) {
      if (!(this_present_usesFeatureList && that_present_usesFeatureList))
        return false;
      if (!this.usesFeatureList.equals(that.usesFeatureList))
        return false;
    }

    boolean this_present_minSDK = true;
    boolean that_present_minSDK = true;
    if (this_present_minSDK || that_present_minSDK) {
      if (!(this_present_minSDK && that_present_minSDK))
        return false;
      if (this.minSDK != that.minSDK)
        return false;
    }

    boolean this_present_targetSDK = true;
    boolean that_present_targetSDK = true;
    if (this_present_targetSDK || that_present_targetSDK) {
      if (!(this_present_targetSDK && that_present_targetSDK))
        return false;
      if (this.targetSDK != that.targetSDK)
        return false;
    }

    boolean this_present_smallScreen = true;
    boolean that_present_smallScreen = true;
    if (this_present_smallScreen || that_present_smallScreen) {
      if (!(this_present_smallScreen && that_present_smallScreen))
        return false;
      if (this.smallScreen != that.smallScreen)
        return false;
    }

    boolean this_present_normalScreen = true;
    boolean that_present_normalScreen = true;
    if (this_present_normalScreen || that_present_normalScreen) {
      if (!(this_present_normalScreen && that_present_normalScreen))
        return false;
      if (this.normalScreen != that.normalScreen)
        return false;
    }

    boolean this_present_largeScreen = true;
    boolean that_present_largeScreen = true;
    if (this_present_largeScreen || that_present_largeScreen) {
      if (!(this_present_largeScreen && that_present_largeScreen))
        return false;
      if (this.largeScreen != that.largeScreen)
        return false;
    }

    boolean this_present_xlargeScreen = true;
    boolean that_present_xlargeScreen = true;
    if (this_present_xlargeScreen || that_present_xlargeScreen) {
      if (!(this_present_xlargeScreen && that_present_xlargeScreen))
        return false;
      if (this.xlargeScreen != that.xlargeScreen)
        return false;
    }

    boolean this_present_signature = true && this.isSetSignature();
    boolean that_present_signature = true && that.isSetSignature();
    if (this_present_signature || that_present_signature) {
      if (!(this_present_signature && that_present_signature))
        return false;
      if (!this.signature.equals(that.signature))
        return false;
    }

    boolean this_present_icon = true && this.isSetIcon();
    boolean that_present_icon = true && that.isSetIcon();
    if (this_present_icon || that_present_icon) {
      if (!(this_present_icon && that_present_icon))
        return false;
      if (!this.icon.equals(that.icon))
        return false;
    }

    boolean this_present_appName = true && this.isSetAppName();
    boolean that_present_appName = true && that.isSetAppName();
    if (this_present_appName || that_present_appName) {
      if (!(this_present_appName && that_present_appName))
        return false;
      if (!this.appName.equals(that.appName))
        return false;
    }

    boolean this_present_AdsList = true && this.isSetAdsList();
    boolean that_present_AdsList = true && that.isSetAdsList();
    if (this_present_AdsList || that_present_AdsList) {
      if (!(this_present_AdsList && that_present_AdsList))
        return false;
      if (!this.AdsList.equals(that.AdsList))
        return false;
    }

    boolean this_present_apkSize = true;
    boolean that_present_apkSize = true;
    if (this_present_apkSize || that_present_apkSize) {
      if (!(this_present_apkSize && that_present_apkSize))
        return false;
      if (this.apkSize != that.apkSize)
        return false;
    }

    boolean this_present_securityLevel = true && this.isSetSecurityLevel();
    boolean that_present_securityLevel = true && that.isSetSecurityLevel();
    if (this_present_securityLevel || that_present_securityLevel) {
      if (!(this_present_securityLevel && that_present_securityLevel))
        return false;
      if (this.securityLevel != that.securityLevel)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(ApkFullProperty other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    ApkFullProperty typedOther = (ApkFullProperty)other;

    lastComparison = Boolean.valueOf(isSetPackageName()).compareTo(typedOther.isSetPackageName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPackageName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.packageName, typedOther.packageName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetVersionName()).compareTo(typedOther.isSetVersionName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVersionName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.versionName, typedOther.versionName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetVersionCode()).compareTo(typedOther.isSetVersionCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVersionCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.versionCode, typedOther.versionCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsesPermissonList()).compareTo(typedOther.isSetUsesPermissonList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsesPermissonList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usesPermissonList, typedOther.usesPermissonList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsesFeatureList()).compareTo(typedOther.isSetUsesFeatureList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsesFeatureList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usesFeatureList, typedOther.usesFeatureList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMinSDK()).compareTo(typedOther.isSetMinSDK());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMinSDK()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.minSDK, typedOther.minSDK);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTargetSDK()).compareTo(typedOther.isSetTargetSDK());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTargetSDK()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.targetSDK, typedOther.targetSDK);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSmallScreen()).compareTo(typedOther.isSetSmallScreen());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSmallScreen()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.smallScreen, typedOther.smallScreen);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNormalScreen()).compareTo(typedOther.isSetNormalScreen());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNormalScreen()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.normalScreen, typedOther.normalScreen);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLargeScreen()).compareTo(typedOther.isSetLargeScreen());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLargeScreen()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.largeScreen, typedOther.largeScreen);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetXlargeScreen()).compareTo(typedOther.isSetXlargeScreen());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetXlargeScreen()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.xlargeScreen, typedOther.xlargeScreen);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSignature()).compareTo(typedOther.isSetSignature());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSignature()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.signature, typedOther.signature);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIcon()).compareTo(typedOther.isSetIcon());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIcon()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.icon, typedOther.icon);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAppName()).compareTo(typedOther.isSetAppName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAppName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.appName, typedOther.appName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAdsList()).compareTo(typedOther.isSetAdsList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAdsList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.AdsList, typedOther.AdsList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetApkSize()).compareTo(typedOther.isSetApkSize());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetApkSize()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.apkSize, typedOther.apkSize);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSecurityLevel()).compareTo(typedOther.isSetSecurityLevel());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSecurityLevel()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.securityLevel, typedOther.securityLevel);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ApkFullProperty(");
    boolean first = true;

    sb.append("packageName:");
    if (this.packageName == null) {
      sb.append("null");
    } else {
      sb.append(this.packageName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("versionName:");
    if (this.versionName == null) {
      sb.append("null");
    } else {
      sb.append(this.versionName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("versionCode:");
    if (this.versionCode == null) {
      sb.append("null");
    } else {
      sb.append(this.versionCode);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usesPermissonList:");
    if (this.usesPermissonList == null) {
      sb.append("null");
    } else {
      sb.append(this.usesPermissonList);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usesFeatureList:");
    if (this.usesFeatureList == null) {
      sb.append("null");
    } else {
      sb.append(this.usesFeatureList);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("minSDK:");
    sb.append(this.minSDK);
    first = false;
    if (!first) sb.append(", ");
    sb.append("targetSDK:");
    sb.append(this.targetSDK);
    first = false;
    if (!first) sb.append(", ");
    sb.append("smallScreen:");
    sb.append(this.smallScreen);
    first = false;
    if (!first) sb.append(", ");
    sb.append("normalScreen:");
    sb.append(this.normalScreen);
    first = false;
    if (!first) sb.append(", ");
    sb.append("largeScreen:");
    sb.append(this.largeScreen);
    first = false;
    if (!first) sb.append(", ");
    sb.append("xlargeScreen:");
    sb.append(this.xlargeScreen);
    first = false;
    if (!first) sb.append(", ");
    sb.append("signature:");
    if (this.signature == null) {
      sb.append("null");
    } else {
      sb.append(this.signature);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("icon:");
    if (this.icon == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.icon, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("appName:");
    if (this.appName == null) {
      sb.append("null");
    } else {
      sb.append(this.appName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("AdsList:");
    if (this.AdsList == null) {
      sb.append("null");
    } else {
      sb.append(this.AdsList);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("apkSize:");
    sb.append(this.apkSize);
    first = false;
    if (isSetSecurityLevel()) {
      if (!first) sb.append(", ");
      sb.append("securityLevel:");
      sb.append(this.securityLevel);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (packageName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'packageName' was not present! Struct: " + toString());
    }
    if (versionName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'versionName' was not present! Struct: " + toString());
    }
    if (versionCode == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'versionCode' was not present! Struct: " + toString());
    }
    if (usesPermissonList == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'usesPermissonList' was not present! Struct: " + toString());
    }
    if (usesFeatureList == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'usesFeatureList' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'minSDK' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'targetSDK' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'smallScreen' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'normalScreen' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'largeScreen' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'xlargeScreen' because it's a primitive and you chose the non-beans generator.
    if (signature == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'signature' was not present! Struct: " + toString());
    }
    if (icon == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'icon' was not present! Struct: " + toString());
    }
    if (appName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'appName' was not present! Struct: " + toString());
    }
    if (AdsList == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'AdsList' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'apkSize' because it's a primitive and you chose the non-beans generator.
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ApkFullPropertyStandardSchemeFactory implements SchemeFactory {
    public ApkFullPropertyStandardScheme getScheme() {
      return new ApkFullPropertyStandardScheme();
    }
  }

  private static class ApkFullPropertyStandardScheme extends StandardScheme<ApkFullProperty> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ApkFullProperty struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PACKAGE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.packageName = iprot.readString();
              struct.setPackageNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // VERSION_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.versionName = iprot.readString();
              struct.setVersionNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // VERSION_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.versionCode = iprot.readString();
              struct.setVersionCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // USES_PERMISSON_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.usesPermissonList = new ArrayList<String>(_list0.size);
                for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                {
                  String _elem2; // required
                  _elem2 = iprot.readString();
                  struct.usesPermissonList.add(_elem2);
                }
                iprot.readListEnd();
              }
              struct.setUsesPermissonListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // USES_FEATURE_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list3 = iprot.readListBegin();
                struct.usesFeatureList = new ArrayList<String>(_list3.size);
                for (int _i4 = 0; _i4 < _list3.size; ++_i4)
                {
                  String _elem5; // required
                  _elem5 = iprot.readString();
                  struct.usesFeatureList.add(_elem5);
                }
                iprot.readListEnd();
              }
              struct.setUsesFeatureListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // MIN_SDK
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.minSDK = iprot.readI32();
              struct.setMinSDKIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // TARGET_SDK
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.targetSDK = iprot.readI32();
              struct.setTargetSDKIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // SMALL_SCREEN
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.smallScreen = iprot.readBool();
              struct.setSmallScreenIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // NORMAL_SCREEN
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.normalScreen = iprot.readBool();
              struct.setNormalScreenIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // LARGE_SCREEN
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.largeScreen = iprot.readBool();
              struct.setLargeScreenIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // XLARGE_SCREEN
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.xlargeScreen = iprot.readBool();
              struct.setXlargeScreenIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // SIGNATURE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.signature = iprot.readString();
              struct.setSignatureIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // ICON
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.icon = iprot.readBinary();
              struct.setIconIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 14: // APP_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map6 = iprot.readMapBegin();
                struct.appName = new HashMap<String,String>(2*_map6.size);
                for (int _i7 = 0; _i7 < _map6.size; ++_i7)
                {
                  String _key8; // required
                  String _val9; // required
                  _key8 = iprot.readString();
                  _val9 = iprot.readString();
                  struct.appName.put(_key8, _val9);
                }
                iprot.readMapEnd();
              }
              struct.setAppNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 15: // ADS_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list10 = iprot.readListBegin();
                struct.AdsList = new ArrayList<String>(_list10.size);
                for (int _i11 = 0; _i11 < _list10.size; ++_i11)
                {
                  String _elem12; // required
                  _elem12 = iprot.readString();
                  struct.AdsList.add(_elem12);
                }
                iprot.readListEnd();
              }
              struct.setAdsListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 16: // APK_SIZE
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.apkSize = iprot.readDouble();
              struct.setApkSizeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 17: // SECURITY_LEVEL
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.securityLevel = iprot.readI32();
              struct.setSecurityLevelIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetMinSDK()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'minSDK' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetTargetSDK()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'targetSDK' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetSmallScreen()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'smallScreen' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetNormalScreen()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'normalScreen' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetLargeScreen()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'largeScreen' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetXlargeScreen()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'xlargeScreen' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetApkSize()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'apkSize' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ApkFullProperty struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.packageName != null) {
        oprot.writeFieldBegin(PACKAGE_NAME_FIELD_DESC);
        oprot.writeString(struct.packageName);
        oprot.writeFieldEnd();
      }
      if (struct.versionName != null) {
        oprot.writeFieldBegin(VERSION_NAME_FIELD_DESC);
        oprot.writeString(struct.versionName);
        oprot.writeFieldEnd();
      }
      if (struct.versionCode != null) {
        oprot.writeFieldBegin(VERSION_CODE_FIELD_DESC);
        oprot.writeString(struct.versionCode);
        oprot.writeFieldEnd();
      }
      if (struct.usesPermissonList != null) {
        oprot.writeFieldBegin(USES_PERMISSON_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.usesPermissonList.size()));
          for (String _iter13 : struct.usesPermissonList)
          {
            oprot.writeString(_iter13);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.usesFeatureList != null) {
        oprot.writeFieldBegin(USES_FEATURE_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.usesFeatureList.size()));
          for (String _iter14 : struct.usesFeatureList)
          {
            oprot.writeString(_iter14);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(MIN_SDK_FIELD_DESC);
      oprot.writeI32(struct.minSDK);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TARGET_SDK_FIELD_DESC);
      oprot.writeI32(struct.targetSDK);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SMALL_SCREEN_FIELD_DESC);
      oprot.writeBool(struct.smallScreen);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(NORMAL_SCREEN_FIELD_DESC);
      oprot.writeBool(struct.normalScreen);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(LARGE_SCREEN_FIELD_DESC);
      oprot.writeBool(struct.largeScreen);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(XLARGE_SCREEN_FIELD_DESC);
      oprot.writeBool(struct.xlargeScreen);
      oprot.writeFieldEnd();
      if (struct.signature != null) {
        oprot.writeFieldBegin(SIGNATURE_FIELD_DESC);
        oprot.writeString(struct.signature);
        oprot.writeFieldEnd();
      }
      if (struct.icon != null) {
        oprot.writeFieldBegin(ICON_FIELD_DESC);
        oprot.writeBinary(struct.icon);
        oprot.writeFieldEnd();
      }
      if (struct.appName != null) {
        oprot.writeFieldBegin(APP_NAME_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.appName.size()));
          for (Map.Entry<String, String> _iter15 : struct.appName.entrySet())
          {
            oprot.writeString(_iter15.getKey());
            oprot.writeString(_iter15.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.AdsList != null) {
        oprot.writeFieldBegin(ADS_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.AdsList.size()));
          for (String _iter16 : struct.AdsList)
          {
            oprot.writeString(_iter16);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(APK_SIZE_FIELD_DESC);
      oprot.writeDouble(struct.apkSize);
      oprot.writeFieldEnd();
      if (struct.isSetSecurityLevel()) {
        oprot.writeFieldBegin(SECURITY_LEVEL_FIELD_DESC);
        oprot.writeI32(struct.securityLevel);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ApkFullPropertyTupleSchemeFactory implements SchemeFactory {
    public ApkFullPropertyTupleScheme getScheme() {
      return new ApkFullPropertyTupleScheme();
    }
  }

  private static class ApkFullPropertyTupleScheme extends TupleScheme<ApkFullProperty> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ApkFullProperty struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.packageName);
      oprot.writeString(struct.versionName);
      oprot.writeString(struct.versionCode);
      {
        oprot.writeI32(struct.usesPermissonList.size());
        for (String _iter17 : struct.usesPermissonList)
        {
          oprot.writeString(_iter17);
        }
      }
      {
        oprot.writeI32(struct.usesFeatureList.size());
        for (String _iter18 : struct.usesFeatureList)
        {
          oprot.writeString(_iter18);
        }
      }
      oprot.writeI32(struct.minSDK);
      oprot.writeI32(struct.targetSDK);
      oprot.writeBool(struct.smallScreen);
      oprot.writeBool(struct.normalScreen);
      oprot.writeBool(struct.largeScreen);
      oprot.writeBool(struct.xlargeScreen);
      oprot.writeString(struct.signature);
      oprot.writeBinary(struct.icon);
      {
        oprot.writeI32(struct.appName.size());
        for (Map.Entry<String, String> _iter19 : struct.appName.entrySet())
        {
          oprot.writeString(_iter19.getKey());
          oprot.writeString(_iter19.getValue());
        }
      }
      {
        oprot.writeI32(struct.AdsList.size());
        for (String _iter20 : struct.AdsList)
        {
          oprot.writeString(_iter20);
        }
      }
      oprot.writeDouble(struct.apkSize);
      BitSet optionals = new BitSet();
      if (struct.isSetSecurityLevel()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetSecurityLevel()) {
        oprot.writeI32(struct.securityLevel);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ApkFullProperty struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.packageName = iprot.readString();
      struct.setPackageNameIsSet(true);
      struct.versionName = iprot.readString();
      struct.setVersionNameIsSet(true);
      struct.versionCode = iprot.readString();
      struct.setVersionCodeIsSet(true);
      {
        org.apache.thrift.protocol.TList _list21 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
        struct.usesPermissonList = new ArrayList<String>(_list21.size);
        for (int _i22 = 0; _i22 < _list21.size; ++_i22)
        {
          String _elem23; // required
          _elem23 = iprot.readString();
          struct.usesPermissonList.add(_elem23);
        }
      }
      struct.setUsesPermissonListIsSet(true);
      {
        org.apache.thrift.protocol.TList _list24 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
        struct.usesFeatureList = new ArrayList<String>(_list24.size);
        for (int _i25 = 0; _i25 < _list24.size; ++_i25)
        {
          String _elem26; // required
          _elem26 = iprot.readString();
          struct.usesFeatureList.add(_elem26);
        }
      }
      struct.setUsesFeatureListIsSet(true);
      struct.minSDK = iprot.readI32();
      struct.setMinSDKIsSet(true);
      struct.targetSDK = iprot.readI32();
      struct.setTargetSDKIsSet(true);
      struct.smallScreen = iprot.readBool();
      struct.setSmallScreenIsSet(true);
      struct.normalScreen = iprot.readBool();
      struct.setNormalScreenIsSet(true);
      struct.largeScreen = iprot.readBool();
      struct.setLargeScreenIsSet(true);
      struct.xlargeScreen = iprot.readBool();
      struct.setXlargeScreenIsSet(true);
      struct.signature = iprot.readString();
      struct.setSignatureIsSet(true);
      struct.icon = iprot.readBinary();
      struct.setIconIsSet(true);
      {
        org.apache.thrift.protocol.TMap _map27 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
        struct.appName = new HashMap<String,String>(2*_map27.size);
        for (int _i28 = 0; _i28 < _map27.size; ++_i28)
        {
          String _key29; // required
          String _val30; // required
          _key29 = iprot.readString();
          _val30 = iprot.readString();
          struct.appName.put(_key29, _val30);
        }
      }
      struct.setAppNameIsSet(true);
      {
        org.apache.thrift.protocol.TList _list31 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
        struct.AdsList = new ArrayList<String>(_list31.size);
        for (int _i32 = 0; _i32 < _list31.size; ++_i32)
        {
          String _elem33; // required
          _elem33 = iprot.readString();
          struct.AdsList.add(_elem33);
        }
      }
      struct.setAdsListIsSet(true);
      struct.apkSize = iprot.readDouble();
      struct.setApkSizeIsSet(true);
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.securityLevel = iprot.readI32();
        struct.setSecurityLevelIsSet(true);
      }
    }
  }

}

