/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "GetApkInfo_constants.h"

namespace com { namespace jike { namespace mobile { namespace appsearch { namespace thirft {

const GetApkInfoConstants g_GetApkInfo_constants;

GetApkInfoConstants::GetApkInfoConstants() {
}

}}}}} // namespace

