// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "GetApkInfo.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::com::jike::mobile::appsearch::thirft;

class GetApkInfoHandler : virtual public GetApkInfoIf {
 public:
  GetApkInfoHandler() {
    // Your initialization goes here
  }

  void getApkFullProperty(ApkFullProperty& _return, const std::string& apkKey) {
    // Your implementation goes here
    printf("getApkFullProperty\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<GetApkInfoHandler> handler(new GetApkInfoHandler());
  shared_ptr<TProcessor> processor(new GetApkInfoProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

