/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef GetApkInfo_CONSTANTS_H
#define GetApkInfo_CONSTANTS_H

#include "GetApkInfo_types.h"

namespace com { namespace jike { namespace mobile { namespace appsearch { namespace thirft {

class GetApkInfoConstants {
 public:
  GetApkInfoConstants();

};

extern const GetApkInfoConstants g_GetApkInfo_constants;

}}}}} // namespace

#endif
